# app/config/security.yml

security:
    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12
            BackOfficeBundle\Entity\Administrateur:
                 algorithm: bcrypt
            BackOfficeBundle\Entity\Collaborateur:
                 algorithm: bcrypt


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
            administrators:
                entity: { class: BackOfficeBundle:Administrateur, property: username }
            users:
                entity: { class: BackOfficeBundle:Collaborateur, property: email }


    firewalls:

            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false

            front:
                pattern:   ^/collaborateur
                anonymous: ~
                provider: users

                form_login:
                    login_path: /collaborateur/login
                    check_path: /collaborateur/login_check
                    default_target_path: /collaborateur

                logout:
                    path:   /collaborateur/logout
                    target: /collaborateur/login
            back:
                pattern:   ^/platform
                anonymous: ~
                provider: administrators

                form_login:
                    login_path: /platform/login
                    check_path: /platform/login_check
                    default_target_path: /platform

                logout:
                    path:   /platform/logout
                    target: /platform/login

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
         - { path: ^/platform/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/platform, roles: ROLE_ADMIN }
         - { path: ^/collaborateur/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/collaborateur, roles: ROLE_USER }