<?php

namespace BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTacheRepository extends EntityRepository
{
}
