<?php

namespace BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationtRepository extends EntityRepository
{
}
