<?php

namespace BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutProjetRepository extends EntityRepository
{
}
