<?php

namespace BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagsPosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsPosteRepository extends EntityRepository
{
}
