<?php

namespace Proxies\__CG__\BackOfficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projet extends \BackOfficeBundle\Entity\Projet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'titre', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'datedebut', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'datefin', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'datelivraison', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'montant', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'statutprojet', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'typeprojet', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'client');
        }

        return array('__isInitialized__', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'titre', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'datedebut', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'datefin', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'datelivraison', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'montant', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'statutprojet', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'typeprojet', '' . "\0" . 'BackOfficeBundle\\Entity\\Projet' . "\0" . 'client');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Projet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedebut($datedebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedebut', array($datedebut));

        return parent::setDatedebut($datedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedebut', array());

        return parent::getDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefin($datefin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefin', array($datefin));

        return parent::setDatefin($datefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefin', array());

        return parent::getDatefin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatelivraison($datelivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatelivraison', array($datelivraison));

        return parent::setDatelivraison($datelivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatelivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatelivraison', array());

        return parent::getDatelivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', array($montant));

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', array());

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutprojet(\BackOfficeBundle\Entity\StatutProjet $statutprojet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutprojet', array($statutprojet));

        return parent::setStatutprojet($statutprojet);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutprojet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutprojet', array());

        return parent::getStatutprojet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeprojet(\BackOfficeBundle\Entity\TypeProjet $typeprojet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeprojet', array($typeprojet));

        return parent::setTypeprojet($typeprojet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeprojet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeprojet', array());

        return parent::getTypeprojet();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\BackOfficeBundle\Entity\Client $client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

}
