<?php

namespace Proxies\__CG__\BackOfficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tache extends \BackOfficeBundle\Entity\Tache implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'id', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'titre', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'description', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datecreation', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datedebut', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datefinprevis', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datefinreel', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'projet', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'statuttache');
        }

        return array('__isInitialized__', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'id', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'titre', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'description', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datecreation', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datedebut', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datefinprevis', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'datefinreel', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'projet', '' . "\0" . 'BackOfficeBundle\\Entity\\Tache' . "\0" . 'statuttache');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tache $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemessage($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemessage', array($datecreation));

        return parent::setDatemessage($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', array());

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedebut($datedebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedebut', array($datedebut));

        return parent::setDatedebut($datedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedebut', array());

        return parent::getDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefinprevis($datefinprevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefinprevis', array($datefinprevis));

        return parent::setDatefinprevis($datefinprevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefinprevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefinprevis', array());

        return parent::getDatefinprevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefinreel($datefinreel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefinreel', array($datefinreel));

        return parent::setDatefinreel($datefinreel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefinreel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefinreel', array());

        return parent::getDatefinreel();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', array($datecreation));

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function setProjet(\BackOfficeBundle\Entity\Projet $projet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjet', array($projet));

        return parent::setProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjet', array());

        return parent::getProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatuttache(\BackOfficeBundle\Entity\StatutTache $statuttache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatuttache', array($statuttache));

        return parent::setStatuttache($statuttache);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatuttache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatuttache', array());

        return parent::getStatuttache();
    }

}
